/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo10.messenger;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FontMetrics;
import java.awt.GridLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JTextArea;

/**
 *
 * @author Usuario
 */
public class Main extends javax.swing.JFrame {
    private static Main mainFrame;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barra = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        contenedorBotonesMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        listaMenu = new javax.swing.JPanel();
        chat = new javax.swing.JPanel();
        BarraDeChat = new javax.swing.JPanel();
        ContenedorEnviarMsj = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        botonEnviar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ScrollPaneMensaje = new javax.swing.JScrollPane();
        textAreaMensaje = new javax.swing.JTextArea();
        scrollChatBody = new javax.swing.JScrollPane();
        chatBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 650));

        barra.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1073, Short.MAX_VALUE)
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        getContentPane().add(barra, java.awt.BorderLayout.PAGE_START);

        menu.setLayout(new java.awt.BorderLayout());

        contenedorBotonesMenu.setBackground(new java.awt.Color(204, 204, 255));
        contenedorBotonesMenu.setLayout(new java.awt.GridLayout(1, 2));

        jButton1.setText("CHATS");
        contenedorBotonesMenu.add(jButton1);

        jButton2.setText("AGENDA");
        contenedorBotonesMenu.add(jButton2);

        menu.add(contenedorBotonesMenu, java.awt.BorderLayout.PAGE_START);

        listaMenu.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout listaMenuLayout = new javax.swing.GroupLayout(listaMenu);
        listaMenu.setLayout(listaMenuLayout);
        listaMenuLayout.setHorizontalGroup(
            listaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        listaMenuLayout.setVerticalGroup(
            listaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        menu.add(listaMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        chat.setLayout(new java.awt.BorderLayout());

        BarraDeChat.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout BarraDeChatLayout = new javax.swing.GroupLayout(BarraDeChat);
        BarraDeChat.setLayout(BarraDeChatLayout);
        BarraDeChatLayout.setHorizontalGroup(
            BarraDeChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        BarraDeChatLayout.setVerticalGroup(
            BarraDeChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        chat.add(BarraDeChat, java.awt.BorderLayout.PAGE_START);

        ContenedorEnviarMsj.setBackground(new java.awt.Color(0, 102, 51));
        ContenedorEnviarMsj.setMinimumSize(new java.awt.Dimension(705, 100));
        ContenedorEnviarMsj.setLayout(new java.awt.BorderLayout());

        botonEnviar.setText("enviar");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        ContenedorEnviarMsj.add(jPanel4, java.awt.BorderLayout.LINE_END);

        ScrollPaneMensaje.setVerticalScrollBar(new ScrollBar());
        ScrollPaneMensaje.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textAreaMensaje.setColumns(20);
        textAreaMensaje.setLineWrap(true);
        textAreaMensaje.setRows(5);
        textAreaMensaje.setAutoscrolls(false);
        textAreaMensaje.setMargin(new java.awt.Insets(0, 10, 10, 20));
        ScrollPaneMensaje.setViewportView(textAreaMensaje);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ScrollPaneMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ScrollPaneMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        ContenedorEnviarMsj.add(jPanel5, java.awt.BorderLayout.CENTER);

        chat.add(ContenedorEnviarMsj, java.awt.BorderLayout.PAGE_END);

        scrollChatBody.setVerticalScrollBar(new ScrollBar());
        scrollChatBody.setViewportView(chatBody);

        chatBody.setLayout(new javax.swing.BoxLayout(chatBody, javax.swing.BoxLayout.PAGE_AXIS));
        scrollChatBody.setViewportView(chatBody);

        chat.add(scrollChatBody, java.awt.BorderLayout.CENTER);

        getContentPane().add(chat, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        String txt = textAreaMensaje.getText();
        mainFrame.addMsj(txt,false);
    }//GEN-LAST:event_botonEnviarActionPerformed

  public void addMsj(String text,boolean d)
    {
        Mensaje m =  new Mensaje(d,text);
        chatBody.add(m);
        chatBody.revalidate(); // Revalida el layout del contenedor para mostrar el mensaje
        chatBody.repaint(); // Vuelve a pintar el contenedor
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            mainFrame = new Main();
            mainFrame.setVisible(true); // Hacer visible el formulario
            mainFrame.addMsj("HOLA MUNDO",true);
            mainFrame.addMsj("Lorem ipsum dolor sit amet, consectetur adipiscing elit Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraDeChat;
    private javax.swing.JPanel ContenedorEnviarMsj;
    private javax.swing.JScrollPane ScrollPaneMensaje;
    private javax.swing.JPanel barra;
    private javax.swing.JButton botonEnviar;
    private javax.swing.JPanel chat;
    private javax.swing.JPanel chatBody;
    private javax.swing.JPanel contenedorBotonesMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel listaMenu;
    private javax.swing.JPanel menu;
    private javax.swing.JScrollPane scrollChatBody;
    private javax.swing.JTextArea textAreaMensaje;
    // End of variables declaration//GEN-END:variables
}
