/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;


import resources.Constantes;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class ConversacionItemList extends MenuItemList {
    private ActionListener controlador;
    
    /**
     * Creates new form NewJPanel1
     */
    public ConversacionItemList(ActionListener controlador, String nickname) {
        initComponents();
        this.controlador = controlador;
        this.nicknameLabel.setText(nickname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelNickname = new javax.swing.JPanel();
        nicknameLabel = new javax.swing.JLabel();
        ultimoMensajeLabel = new javax.swing.JLabel();
        panelNotificacion = new javax.swing.JPanel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(47, 52, 52));
        jPanel1.setMaximumSize(new java.awt.Dimension(111, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(111, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chat.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(111, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(111, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(111, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        panelNickname.setBackground(new java.awt.Color(47, 52, 52));

        nicknameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nicknameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nicknameLabel.setText("COMPANY");

        ultimoMensajeLabel.setForeground(new java.awt.Color(210, 210, 210));

        panelNotificacion.setBackground(Constantes.COLOR_NOTIFICACION);
        panelNotificacion.setVisible(false);

        javax.swing.GroupLayout panelNotificacionLayout = new javax.swing.GroupLayout(panelNotificacion);
        panelNotificacion.setLayout(panelNotificacionLayout);
        panelNotificacionLayout.setHorizontalGroup(
            panelNotificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        panelNotificacionLayout.setVerticalGroup(
            panelNotificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelNicknameLayout = new javax.swing.GroupLayout(panelNickname);
        panelNickname.setLayout(panelNicknameLayout);
        panelNicknameLayout.setHorizontalGroup(
            panelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNicknameLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelNicknameLayout.createSequentialGroup()
                        .addComponent(nicknameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ultimoMensajeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelNicknameLayout.setVerticalGroup(
            panelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNicknameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nicknameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ultimoMensajeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(panelNickname, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // Cambiar el color de fondo a celeste claro cuando el mouse entra
        panelNickname.setBackground(Constantes.COLOR_HOVER); // Celeste claro (Light Cyan)
        nicknameLabel.setForeground(new Color(30,30,30));
        ultimoMensajeLabel.setForeground(new Color(50,50,50));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        panelNickname.setBackground(Constantes.COLOR_BASE); // Celeste claro (Light Cyan)
        nicknameLabel.setForeground(new Color(255,255,255));
        ultimoMensajeLabel.setForeground(new Color(210,210,210));
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        panelNotificacion.setVisible(false);
        ActionEvent event = new ActionEvent(nicknameLabel.getText(), ActionEvent.ACTION_PERFORMED, "VER CONVERSACION");
        controlador.actionPerformed(event);
    }//GEN-LAST:event_formMouseClicked

    public JLabel getNicknameLabel() {
        return nicknameLabel;
    }

    public JLabel getUltimoMensajeLabel() {
        return ultimoMensajeLabel;
    }
    
    public JPanel getPanelNickname()
    {
        return panelNickname;
    }
    
    public void setNotificacion()
    {
        panelNotificacion.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JPanel panelNickname;
    private javax.swing.JPanel panelNotificacion;
    private javax.swing.JLabel ultimoMensajeLabel;
    // End of variables declaration//GEN-END:variables
}
