package vista;

import resources.Constantes;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JScrollBar;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author vanci
 */
public class FormularioAgregar extends javax.swing.JDialog implements IFormulario{
    FormularioItemList itemSeleccionado = null;
    

    public FormularioAgregar(JFrame vista, boolean b, ActionListener controlador, String actionCommand, String textoButton) {
        super(vista, b);
        setLocationRelativeTo(null);
        initComponents();
        agregarButton.addActionListener(controlador);
        agregarButton.setEnabled(false);
        agregarButton.setActionCommand(actionCommand);
        agregarButton.setText(textoButton);
    }
    
    public void agregarContactos(ArrayList<String> contactos)
    {
        FormularioItemList item;
        for(String contactoNickname:contactos)
        {
            item = new FormularioItemList(this,contactoNickname);
            this.agregarItem(item);
        }
    }
    
    private void agregarItem(FormularioItemList item)
    {
        contactosPanel.add(item);
        contactosPanel.revalidate();
        contactosPanel.repaint();
    }
    
    public void setItemSeleccionado(FormularioItemList item)
    {
        if(itemSeleccionado != null)
            itemSeleccionado.reestablecerFondo();
        this.itemSeleccionado = item;
        agregarButton.setEnabled(true);
    }
    
    public String getNickname() {
        return this.itemSeleccionado.getNickname();
    }
    
    public void abrirFormulario(ArrayList<String> contactos) {
        this.agregarContactos(contactos);
        this.setVisible(true);
    }

    public void cerrarFormulario() {
        this.setVisible(false);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        agregarButton = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();
        scrollContactos = new javax.swing.JScrollPane();
        contactosPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Messenger - Formulario Agregar Conversacion");
        setResizable(false);

        panelPrincipal.setBackground(Constantes.COLOR_BASE);

        agregarButton.setBackground(Constantes.COLOR_BOTON);
        agregarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregarButton.setForeground(new Color(255,255,255));
        agregarButton.setText("Agendar contacto");
        agregarButton.setActionCommand("AGREGAR CONVERSACION");
        agregarButton.setEnabled(false);

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("SELECCIONAR CONTACTO");

        JScrollBar scrollBar = new JScrollBar();
        scrollBar.setUI(new ModernScrollBarUI());
        scrollContactos.setVerticalScrollBar(scrollBar);
        scrollContactos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        contactosPanel.setBackground(new java.awt.Color(47, 52, 52));
        contactosPanel.setLayout(new javax.swing.BoxLayout(contactosPanel, javax.swing.BoxLayout.Y_AXIS));
        scrollContactos.setViewportView(contactosPanel);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollContactos))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(93, 93, 93))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addComponent(scrollContactos, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(agregarButton)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JPanel contactosPanel;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scrollContactos;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void abrirFormulario() {
    }

}
