/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import directorio.IDirectorioListener;
import directorio.InfoServidor;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.text.BadLocationException;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Usuario
 */
public class VentanaDirectorio extends javax.swing.JFrame implements IDirectorioListener{

    /**
     * Creates new form VentanaDirectorio
     */
    public VentanaDirectorio() {
        initComponents();
        this.listaIp.setEditable(false);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Actualiza la vista con la informacion sobre los servidores registrados en el directorio
     * @param servidores 
     */
    public void actualizarVista(ArrayList<InfoServidor> servidores) {
        listaIp.setText("");
        listaEstado.setText("");
        listaPuerto.setText("");
        listaClientes.setText("");

        try {
            StyledDocument docIP = listaIp.getStyledDocument();
            StyledDocument docEstado = listaEstado.getStyledDocument();
            StyledDocument docPuerto = listaPuerto.getStyledDocument();
            StyledDocument docClientes = listaClientes.getStyledDocument();

            for (InfoServidor servidor : servidores) {
                docIP.insertString(docIP.getLength(), servidor.getIP() + "\n", null);
                docEstado.insertString(docEstado.getLength(), (servidor.estaListo() ? "Activo" : "Inactivo") + "\n", null);
                docPuerto.insertString(docPuerto.getLength(), servidor.getPuertoCliente() + "\n", null);
                docClientes.insertString(docClientes.getLength(), servidor.getCantidadUsuariosActivos() + "\n", null);
            }

        } catch (BadLocationException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelNombre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaIp = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaPuerto = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        listaEstado = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JTextPane();

        jLabel1.setText("jLabel1");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Directorio de servidores");
        setMinimumSize(new java.awt.Dimension(570, 290));

        jPanelNombre.setBackground(new java.awt.Color(47, 52, 52));
        jPanelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jPanelNombre.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanelNombre.setPreferredSize(new java.awt.Dimension(402, 30));
        jPanelNombre.setLayout(new java.awt.GridLayout(1, 4, 0, 3));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("IP");
        jPanelNombre.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Puerto");
        jPanelNombre.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Estado");
        jPanelNombre.add(jLabel4);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cantidad Clientes");
        jPanelNombre.add(jLabel6);

        getContentPane().add(jPanelNombre, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setBackground(new Color(47,52,52));
        jScrollPane2.setBorder(BorderFactory.createLineBorder(new Color(47,52,52), 1));
        jScrollPane2.setBackground(new java.awt.Color(47, 52, 52));

        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 0, 3));

        jScrollPane6.setBackground(new Color(47,52,52));
        jScrollPane6.setBorder(BorderFactory.createLineBorder(new Color(47,52,52), 1));
        jScrollPane6.setBackground(new java.awt.Color(47, 52, 52));

        listaIp.setBackground(new Color(40,40,40));
        listaIp.setForeground(new java.awt.Color(255, 255, 255));
        listaIp.setFocusable(false);
        listaIp.setMaximumSize(new java.awt.Dimension(2147483647, 250));
        listaIp.setPreferredSize(new java.awt.Dimension(120, 100));
        jScrollPane6.setViewportView(listaIp);

        jPanel1.add(jScrollPane6);

        jScrollPane7.setBackground(new Color(47,52,52));
        jScrollPane7.setBorder(BorderFactory.createLineBorder(new Color(47,52,52), 1));
        jScrollPane7.setBackground(new java.awt.Color(47, 52, 52));

        listaPuerto.setBackground(new Color(40,40,40));
        listaPuerto.setForeground(new java.awt.Color(255, 255, 255));
        listaPuerto.setFocusable(false);
        listaPuerto.setMaximumSize(new java.awt.Dimension(2147483647, 293));
        listaPuerto.setName(""); // NOI18N
        listaPuerto.setPreferredSize(new java.awt.Dimension(62, 50));
        jScrollPane7.setViewportView(listaPuerto);

        jPanel1.add(jScrollPane7);

        jScrollPane8.setBorder(BorderFactory.createLineBorder(new Color(47,52,52), 1));
        jScrollPane8.setBackground(new java.awt.Color(47, 52, 52));

        listaEstado.setBackground(new Color(40,40,40));
        listaEstado.setForeground(new java.awt.Color(255, 255, 255));
        listaEstado.setFocusable(false);
        listaEstado.setMaximumSize(new java.awt.Dimension(2147483647, 293));
        listaEstado.setPreferredSize(new java.awt.Dimension(62, 50));
        jScrollPane8.setViewportView(listaEstado);

        jPanel1.add(jScrollPane8);

        jScrollPane9.setBorder(BorderFactory.createLineBorder(new Color(47,52,52), 1));
        jScrollPane9.setBackground(new java.awt.Color(47, 52, 52));

        listaClientes.setBackground(new Color(40,40,40));
        listaClientes.setForeground(new java.awt.Color(255, 255, 255));
        listaClientes.setFocusable(false);
        listaClientes.setMaximumSize(new java.awt.Dimension(2147483647, 293));
        listaClientes.setPreferredSize(new java.awt.Dimension(62, 50));
        jScrollPane9.setViewportView(listaClientes);

        jPanel1.add(jScrollPane9);

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDirectorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelNombre;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane listaClientes;
    private javax.swing.JTextPane listaEstado;
    private javax.swing.JTextPane listaIp;
    private javax.swing.JTextPane listaPuerto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizarEstado(ArrayList<InfoServidor> servidores) {
        actualizarVista(servidores);
    }

    @Override
    public void directorioListo() {
        this.setVisible(true);
    }
}
