/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.event.MouseEvent;

/**
 *
 * @author Usuario
 */
public class AgregarConversacionItemList extends javax.swing.JPanel {
    private FormularioAgregarConversacion agregarConversacion;
    private boolean seleccionado = false;
    
    /**
     * Creates new form NewJPanel1
     */
    public AgregarConversacionItemList() {
        initComponents();
    }
    
    public AgregarConversacionItemList(FormularioAgregarConversacion agregarConversacion,String nickname, String puerto, String ip) {
        initComponents();
        nicknameLabel.setText(nickname);
        puertoLabel.setText(puerto);
        ipLabel.setText(ip);
        this.agregarConversacion = agregarConversacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenContactoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        contenedorPanel = new javax.swing.JPanel();
        nicknameLabel = new javax.swing.JLabel();
        ipLabel = new javax.swing.JLabel();
        puertoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(47, 52, 52));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(371, 100));
        setMinimumSize(new java.awt.Dimension(371, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        imagenContactoPanel.setBackground(new java.awt.Color(47, 52, 52));
        imagenContactoPanel.setMaximumSize(new java.awt.Dimension(111, 100));
        imagenContactoPanel.setMinimumSize(new java.awt.Dimension(111, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chat.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(111, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(111, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(111, 100));

        javax.swing.GroupLayout imagenContactoPanelLayout = new javax.swing.GroupLayout(imagenContactoPanel);
        imagenContactoPanel.setLayout(imagenContactoPanelLayout);
        imagenContactoPanelLayout.setHorizontalGroup(
            imagenContactoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagenContactoPanelLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        imagenContactoPanelLayout.setVerticalGroup(
            imagenContactoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenContactoPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        add(imagenContactoPanel, java.awt.BorderLayout.LINE_START);

        contenedorPanel.setBackground(new java.awt.Color(47, 52, 52));
        contenedorPanel.setOpaque(false);

        nicknameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nicknameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nicknameLabel.setText("COMPANY");

        ipLabel.setForeground(new java.awt.Color(210, 210, 210));
        ipLabel.setText("ip");

        puertoLabel.setText("puerto");

        javax.swing.GroupLayout contenedorPanelLayout = new javax.swing.GroupLayout(contenedorPanel);
        contenedorPanel.setLayout(contenedorPanelLayout);
        contenedorPanelLayout.setHorizontalGroup(
            contenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(contenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puertoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicknameLabel)
                    .addComponent(ipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        contenedorPanelLayout.setVerticalGroup(
            contenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nicknameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puertoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(contenedorPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        contenedorPanel.setOpaque(true);
        contenedorPanel.setBackground(Colores.COLOR_HOVER);     
        nicknameLabel.setForeground(new Color(30,30,30));
        ipLabel.setForeground(new Color(50,50,50));
        puertoLabel.setForeground(new Color(50,50,50));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if(!seleccionado)
        {
            contenedorPanel.setOpaque(false);
            contenedorPanel.setBackground(Colores.COLOR_BASE);
            nicknameLabel.setForeground(new Color(255,255,255));
            ipLabel.setForeground(new Color(210,210,210));
            puertoLabel.setForeground(new Color(210,210,210));
        }
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        contenedorPanel.setOpaque(true);
        this.seleccionado = true;
        agregarConversacion.setItemSeleccionado(this);
        contenedorPanel.setBackground(Colores.COLOR_HOVER); 
        nicknameLabel.setForeground(new Color(30,30,30));
        ipLabel.setForeground(new Color(50,50,50));
        puertoLabel.setForeground(new Color(50,50,50));    
    }//GEN-LAST:event_formMouseClicked

    public void reestablecerFondo()
    {
        MouseEvent e = null;
        this.seleccionado = false;
        this.formMouseExited(e);
    }
    
    public int getPuerto() {
        return Integer.parseInt(puertoLabel.getText());
    }
    
    public String getIp()
    {
        return ipLabel.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorPanel;
    private javax.swing.JPanel imagenContactoPanel;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JLabel puertoLabel;
    // End of variables declaration//GEN-END:variables
}
