/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;


/**
 *
 * @author Usuario
 */
public class ContactoItemList extends MenuItemList {
    /**
     * Creates new form NewJPanel1
     */
    public ContactoItemList(String nickname, String ip, int puerto) {
        initComponents();
        nicknameLabel.setText(nickname);
        ipLabel.setText(ip);
        puertoLabel.setText(String.valueOf(puerto));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelNickname = new javax.swing.JPanel();
        nicknameLabel = new javax.swing.JLabel();
        ipLabel = new javax.swing.JLabel();
        puertoLabel = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(47, 52, 52));
        jPanel1.setMaximumSize(new java.awt.Dimension(111, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(111, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chat.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(111, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(111, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(111, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        panelNickname.setBackground(new java.awt.Color(47, 52, 52));

        nicknameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nicknameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nicknameLabel.setText("COMPANY");

        ipLabel.setForeground(new java.awt.Color(210, 210, 210));
        ipLabel.setText("ip");

        puertoLabel.setForeground(new java.awt.Color(210, 210, 210));
        puertoLabel.setText("puerto");

        javax.swing.GroupLayout panelNicknameLayout = new javax.swing.GroupLayout(panelNickname);
        panelNickname.setLayout(panelNicknameLayout);
        panelNicknameLayout.setHorizontalGroup(
            panelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNicknameLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puertoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicknameLabel)
                    .addComponent(ipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelNicknameLayout.setVerticalGroup(
            panelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNicknameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nicknameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puertoLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(panelNickname, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        panelNickname.setBackground(Colores.COLOR_BASE);
        nicknameLabel.setForeground(new Color(255,255,255));
        ipLabel.setForeground(new Color(210,210,210));
        puertoLabel.setForeground(new Color(210,210,210));
    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        panelNickname.setBackground(Colores.COLOR_HOVER);
        nicknameLabel.setForeground(new Color(30,30,30));
        ipLabel.setForeground(new Color(50,50,50));
        puertoLabel.setForeground(new Color(50,50,50));
    }//GEN-LAST:event_formMouseEntered

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ipLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JPanel panelNickname;
    private javax.swing.JLabel puertoLabel;
    // End of variables declaration//GEN-END:variables
}
