package vista;

import controlador.Control;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JScrollBar;
import modelo.Contacto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author vanci
 */
public class FormularioAgregarConversacion extends javax.swing.JDialog {
    AgregarConversacionItemList itemSeleccionado = null;
    

    public FormularioAgregarConversacion(JFrame vista, boolean b, ActionListener controlador) {
        super(vista, b);
        setLocationRelativeTo(null);
        initComponents();
        agregarConversacionButton.addActionListener(controlador);
        agregarConversacionButton.setEnabled(false);
    }
    
    public void agregarContactos(ArrayList<Contacto> contactos)
    {
        System.out.println("UJHSDAHD");
        AgregarConversacionItemList item;
        for(Contacto contacto:contactos)
        {
            item = new AgregarConversacionItemList(this,contacto.getNickname(),String.valueOf(contacto.getPuerto()),contacto.getIp());
            this.agregarItem(item);
        }
    }
    
    private void agregarItem(AgregarConversacionItemList item)
    {
        contactosPanel.add(item);
        contactosPanel.revalidate();
        contactosPanel.repaint();
    }
    
    public void setItemSeleccionado(AgregarConversacionItemList item)
    {
        if(itemSeleccionado != null)
            itemSeleccionado.reestablecerFondo();
        this.itemSeleccionado = item;
        agregarConversacionButton.setEnabled(true);
    }
    
    public int getPuerto()
    {
        return itemSeleccionado.getPuerto();
    }
    
    public String getIp()
    {
        return itemSeleccionado.getIp();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        agregarConversacionButton = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();
        scrollContactos = new javax.swing.JScrollPane();
        contactosPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Messenger - Formulario Agregar Conversacion");
        setResizable(false);

        panelPrincipal.setBackground(Colores.COLOR_BASE);

        agregarConversacionButton.setBackground(Colores.COLOR_BOTON);
        agregarConversacionButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregarConversacionButton.setForeground(new Color(255,255,255));
        agregarConversacionButton.setText("Agregar conversacion");
        agregarConversacionButton.setActionCommand("AGREGAR CONVERSACION");
        agregarConversacionButton.setEnabled(false);

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("SELECCIONAR CONTACTO");

        JScrollBar scrollBar = new JScrollBar();
        scrollBar.setUI(new ModernScrollBarUI());
        scrollContactos.setVerticalScrollBar(scrollBar);
        scrollContactos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        contactosPanel.setBackground(new java.awt.Color(47, 52, 52));
        contactosPanel.setLayout(new javax.swing.BoxLayout(contactosPanel, javax.swing.BoxLayout.Y_AXIS));
        scrollContactos.setViewportView(contactosPanel);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(93, 93, 93))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarConversacionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(scrollContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addComponent(scrollContactos, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarConversacionButton)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarConversacionButton;
    private javax.swing.JPanel contactosPanel;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scrollContactos;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables

}
