/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import resources.Constantes;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;


/**
 *
 * @author Usuario
 */
public class ContactoItemList extends MenuItemList {
    private ActionListener controlador;
    /**
     * Creates new form NewJPanel1
     */
    public ContactoItemList(ActionListener controlador,String nicknameAgendado, String nicknameReal) {
        initComponents();
        this.controlador = controlador;
        nicknameAgendadoLabel.setText(nicknameAgendado);
        nicknameRealLabel.setText(nicknameReal);
        this.editarContactoButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelNickname = new javax.swing.JPanel();
        nicknameAgendadoLabel = new javax.swing.JLabel();
        editarContactoButton = new javax.swing.JButton();
        nicknameRealLabel = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(47, 52, 52));
        jPanel1.setMaximumSize(new java.awt.Dimension(111, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(111, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chat.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(111, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(111, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(111, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        panelNickname.setBackground(new java.awt.Color(47, 52, 52));

        nicknameAgendadoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nicknameAgendadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        nicknameAgendadoLabel.setText("COMPANY");

        editarContactoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/editarContacto.png"))); // NOI18N
        editarContactoButton.setText("jButton1");
        editarContactoButton.setActionCommand("");
        editarContactoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editarContactoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editarContactoButtonMouseExited(evt);
            }
        });
        editarContactoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarContactoButtonActionPerformed(evt);
            }
        });

        nicknameRealLabel.setForeground(new java.awt.Color(255, 255, 255));
        nicknameRealLabel.setText("nick real");

        javax.swing.GroupLayout panelNicknameLayout = new javax.swing.GroupLayout(panelNickname);
        panelNickname.setLayout(panelNicknameLayout);
        panelNicknameLayout.setHorizontalGroup(
            panelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNicknameLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNicknameLayout.createSequentialGroup()
                        .addComponent(nicknameRealLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(editarContactoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(panelNicknameLayout.createSequentialGroup()
                        .addComponent(nicknameAgendadoLabel)
                        .addContainerGap(131, Short.MAX_VALUE))))
        );
        panelNicknameLayout.setVerticalGroup(
            panelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNicknameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nicknameAgendadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarContactoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicknameRealLabel))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        add(panelNickname, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void setNickname(String nickname)
    {
        nicknameAgendadoLabel.setText(nickname);
    }
    
    public String getNickname()
    {
        return nicknameRealLabel.getText();
    }
    
    private void formMouseEntered(java.awt.event.MouseEvent evt) {
    mantenerHover();
}

    private void formMouseExited(java.awt.event.MouseEvent evt) {
        verificarSalidaDelMouse();
    }

    private void editarContactoButtonMouseEntered(java.awt.event.MouseEvent evt) {
        editarContactoButton.setBorder(BorderFactory.createLineBorder(Constantes.COLOR_NOTIFICACION, 1));
        mantenerHover();
    }

    private void editarContactoButtonMouseExited(java.awt.event.MouseEvent evt) {
        editarContactoButton.setBorder(BorderFactory.createEmptyBorder());
        verificarSalidaDelMouse();
    }

    private void editarContactoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        ActionEvent event = new ActionEvent(nicknameRealLabel.getText(), ActionEvent.ACTION_PERFORMED, "SOLICITUD EDITAR CONTACTO");
        controlador.actionPerformed(event);
    }

    private void mantenerHover() {
        panelNickname.setBackground(Constantes.COLOR_HOVER);
        nicknameAgendadoLabel.setForeground(new Color(30, 30, 30));
        nicknameRealLabel.setForeground(new Color(30, 30, 30));
        editarContactoButton.setVisible(true);
    }

    private void salirHover() {
        panelNickname.setBackground(Constantes.COLOR_BASE);
        nicknameAgendadoLabel.setForeground(Color.WHITE);
        nicknameRealLabel.setForeground(Color.WHITE);
        editarContactoButton.setVisible(false);
    }

    private void verificarSalidaDelMouse() {
        // Obtenemos posición del mouse en pantalla
        Point mouseEnPantalla = MouseInfo.getPointerInfo().getLocation();
        // Convertimos a coordenadas relativas al componente
        SwingUtilities.convertPointFromScreen(mouseEnPantalla, this);
        if (!this.contains(mouseEnPantalla)) {
            salirHover();
        }
}

    /*
    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        panelNickname.setBackground(Constantes.COLOR_BASE);
        nicknameLabel.setForeground(new Color(255,255,255));
        editarContactoButton.setVisible(false);
    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        panelNickname.setBackground(Constantes.COLOR_HOVER);
        nicknameLabel.setForeground(new Color(30,30,30));
        editarContactoButton.setVisible(true);
    }//GEN-LAST:event_formMouseEntered

    private void editarContactoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarContactoButtonActionPerformed
        ActionEvenevent = new ActionEvent(nicknameLabel.getText(), ActionEvent.ACTION_PERFORMED, "SOLICITUD EDITAR CONTACTO");
        controlador.actionPerformed(event);
    }//GEN-LAST:event_editarContactoButtonActionPerformed

    private void editarContactoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarContactoButtonMouseEntered
        editarContactoButton.setBorder(BorderFactory.createLineBorder(Constantes.COLOR_NOTIFICACION, 1));
    }//GEN-LAST:event_editarContactoButtonMouseEntered

    private void editarContactoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarContactoButtonMouseExited
        editarContactoButton.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_editarContactoButtonMouseExited
*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarContactoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nicknameAgendadoLabel;
    private javax.swing.JLabel nicknameRealLabel;
    private javax.swing.JPanel panelNickname;
    // End of variables declaration//GEN-END:variables
}
