/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import resources.Constantes;

/**
 *
 * @author Usuario
 */
public class FormularioPersistencia extends javax.swing.JDialog {  
    private ActionListener controlador;
    private ButtonGroup grupoPersistencia = new ButtonGroup();
    
    /**
     * Creates new form VentanaPersistencia
     */
    public FormularioPersistencia(java.awt.Frame parent, boolean modal, ActionListener controlador) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.controlador = controlador;
        grupoPersistencia.add(xml);
        grupoPersistencia.add(json);
        grupoPersistencia.add(txtplano);
        xml.setActionCommand(Constantes.XML);
        json.setActionCommand(Constantes.JSON);
        txtplano.setActionCommand(Constantes.TEXTO_PLANO);
        json.setSelected(true);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        xml = new javax.swing.JRadioButton();
        txtplano = new javax.swing.JRadioButton();
        json = new javax.swing.JRadioButton();
        botonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Configuracion persistencia");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(47, 52, 52));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipo de persistencia");

        xml.setForeground(new java.awt.Color(255, 255, 255));
        xml.setText("XML");

        txtplano.setForeground(new java.awt.Color(255, 255, 255));
        txtplano.setText("Texto plano");

        json.setForeground(new java.awt.Color(255, 255, 255));
        json.setText("JSON");

        botonConfirmar.setBackground(new java.awt.Color(30, 30, 30));
        botonConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        botonConfirmar.setText("Confirmar");
        botonConfirmar.setActionCommand("ELEGIR PERSISTENCIA");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(xml)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtplano)
                        .addGap(12, 12, 12)
                        .addComponent(json))
                    .addComponent(botonConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xml)
                    .addComponent(json)
                    .addComponent(txtplano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(botonConfirmar)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        String persistencia = grupoPersistencia.getSelection().getActionCommand();
        ActionEvent event = new ActionEvent(persistencia, ActionEvent.ACTION_PERFORMED, "ELEGIR PERSISTENCIA");
        controlador.actionPerformed(event);
        this.dispose();
    }//GEN-LAST:event_botonConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton json;
    private javax.swing.JRadioButton txtplano;
    private javax.swing.JRadioButton xml;
    // End of variables declaration//GEN-END:variables
}
