/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import resources.Constantes;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class FormularioRegistro extends javax.swing.JFrame implements IFormulario {
    private boolean habilitaNickname = false;
    private ButtonGroup tipoArchivo;
    
    public FormularioRegistro(ActionListener controlador) {
        initComponents();
        setBackground(Constantes.COLOR_BASE);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/resources/iconApp.png")).getImage());
        botonConfirmar.addActionListener(controlador);
        botonConfirmar.setEnabled(false);
        tipoArchivo = new ButtonGroup();
        tipoArchivo.add(this.xmlRadioButton);
        tipoArchivo.add(this.jsonRadioButton);
        tipoArchivo.add(this.textoPlanoRadioButton);
        this.xmlRadioButton.setActionCommand(Constantes.XML);
        this.jsonRadioButton.setActionCommand(Constantes.JSON);
        this.textoPlanoRadioButton.setActionCommand(Constantes.TEXTO_PLANO);
        this.xmlRadioButton.setSelected(true);
    }
    
    public String getTipoArchivo(){
        return tipoArchivo.getSelection().getActionCommand();
    }
    
    public String getNickname()
    {
        return textNickname.getText();
    }
     
    public int getPuerto()
    {
        return Integer.parseInt(puertoDirectorioTextField.getText());
    }
    
    public String getIP()
    {
        return ipDirectorioTextField.getText();
    }
    
    private void habilitarBoton(){
        if(habilitaNickname)
            botonConfirmar.setEnabled(true);
        else
            botonConfirmar.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelNickname = new javax.swing.JLabel();
        textNickname = new javax.swing.JTextField();
        botonConfirmar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        ipDirectorioTextField = new javax.swing.JTextField();
        labelNickname1 = new javax.swing.JLabel();
        puertoDirectorioTextField = new javax.swing.JTextField();
        labelNickname2 = new javax.swing.JLabel();
        labelNickname3 = new javax.swing.JLabel();
        xmlRadioButton = new javax.swing.JRadioButton();
        jsonRadioButton = new javax.swing.JRadioButton();
        textoPlanoRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Messenger - Registro");
        setMinimumSize(new java.awt.Dimension(350, 350));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(Constantes.COLOR_BASE);
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 425));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jPanel2.setBackground(Constantes.COLOR_BASE);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 211, 211)));

        labelNickname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNickname.setForeground(new java.awt.Color(255, 255, 255));
        labelNickname.setText("nickname:");

        textNickname.setMinimumSize(new java.awt.Dimension(140, 30));
        textNickname.setPreferredSize(new java.awt.Dimension(140, 30));
        textNickname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textNicknameKeyReleased(evt);
            }
        });

        botonConfirmar.setBackground(Constantes.COLOR_BOTON);
        botonConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonConfirmar.setForeground(new Color(255,255,255));
        botonConfirmar.setText("registrar");
        botonConfirmar.setActionCommand("REGISTRO");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("REGISTRO");

        ipDirectorioTextField.setText("127.0.0.1");
        ipDirectorioTextField.setMinimumSize(new java.awt.Dimension(140, 30));
        ipDirectorioTextField.setPreferredSize(new java.awt.Dimension(140, 30));
        ipDirectorioTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ipDirectorioTextFieldKeyReleased(evt);
            }
        });

        labelNickname1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNickname1.setForeground(new java.awt.Color(255, 255, 255));
        labelNickname1.setText("IP:");

        puertoDirectorioTextField.setText("300");
        puertoDirectorioTextField.setMinimumSize(new java.awt.Dimension(140, 30));
        puertoDirectorioTextField.setPreferredSize(new java.awt.Dimension(140, 30));
        puertoDirectorioTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                puertoDirectorioTextFieldKeyReleased(evt);
            }
        });

        labelNickname2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNickname2.setForeground(new java.awt.Color(255, 255, 255));
        labelNickname2.setText("Puerto:");

        labelNickname3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNickname3.setForeground(new java.awt.Color(255, 255, 255));
        labelNickname3.setText("Tipo de Archivo");

        xmlRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        xmlRadioButton.setBackground(Constantes.COLOR_BASE);
        xmlRadioButton.setText("XML");
        xmlRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xmlRadioButtonActionPerformed(evt);
            }
        });

        jsonRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        jsonRadioButton.setBackground(Constantes.COLOR_BASE);
        jsonRadioButton.setText("JSON");
        jsonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsonRadioButtonActionPerformed(evt);
            }
        });

        textoPlanoRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        textoPlanoRadioButton.setText("Texto Plano");
        textoPlanoRadioButton.setActionCommand("TEXTO_PLANO");
        textoPlanoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPlanoRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelNickname1)
                                                .addComponent(labelNickname2))
                                            .addGap(45, 45, 45))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(labelNickname)
                                            .addGap(18, 18, 18)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(puertoDirectorioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ipDirectorioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(xmlRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(jsonRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(textoPlanoRadioButton)
                                    .addGap(15, 15, 15)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(labelNickname3)))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(69, 69, 69))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipDirectorioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNickname2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puertoDirectorioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNickname3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPlanoRadioButton)
                    .addComponent(jsonRadioButton)
                    .addComponent(xmlRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNicknameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNicknameKeyReleased
        habilitaNickname = !this.textNickname.getText().isEmpty() && this.textNickname.getText().length()<=64;
        habilitarBoton();
    }//GEN-LAST:event_textNicknameKeyReleased

    private void ipDirectorioTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipDirectorioTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ipDirectorioTextFieldKeyReleased

    private void puertoDirectorioTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_puertoDirectorioTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_puertoDirectorioTextFieldKeyReleased

    private void xmlRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmlRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xmlRadioButtonActionPerformed

    private void jsonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsonRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsonRadioButtonActionPerformed

    private void textoPlanoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPlanoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPlanoRadioButtonActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConfirmarActionPerformed

    public void cerrarFormulario() {
       this.dispose();
    }
    
    public void abrirFormulario() {
       this.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JTextField ipDirectorioTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jsonRadioButton;
    private javax.swing.JLabel labelNickname;
    private javax.swing.JLabel labelNickname1;
    private javax.swing.JLabel labelNickname2;
    private javax.swing.JLabel labelNickname3;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField puertoDirectorioTextField;
    private javax.swing.JTextField textNickname;
    private javax.swing.JRadioButton textoPlanoRadioButton;
    private javax.swing.JRadioButton xmlRadioButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void abrirFormulario(ArrayList<String> contactos) {   
    }
}
